### ISSUE TITLE
Newer release plans?

### ISSUE THREAD

**Issue by javidg96** [jpmac26/DRV3-Tools#2]
Hello. I have no other way of contacting you that I know of, so sorry to open an issue when there really are none.
Have you planned to add new releases for the current stable version of the tools? I'm trying to start a translation project, and in order to try to inject new characters (¡/¿; á/í/ó/ú; ñ...) I need a way to unpack and repack srd files.
Sorry to bother you again, all the best!

**Comment by CaptainSwag101** [comment]
Hey there, I'm incredibly sorry for the late reply, but I hope it's better late than never. 

My newer set of tools (DRV3-Sharp) should be capable of working with SRD files to an extent, but if you're looking to modify the font files, those are among the most complicated files we've discovered in the whole game, and we currently don't know when we will support modifying the actual font data.

It's really just me researching most of these formats on my own with the help of a couple friends in our spare time, so sadly progress is very slow, but we understand how important custom fonts are for the fan translation community, so we really want to make it a reality at some point!
